name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  Qt6_VERSION: 6.8.0

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
       choco install -y strawberryperl python ninja cmake git visualstudio2022buildtools visualstudio2022-workload-vctools
       choco install -y aqt --version 3.1.19
       choco install -y opencv --package-parameters "'/InstallationPath:C:\'"
       aqt install-qt --outputdir c:\Qt windows desktop $env:Qt6_VERSION win64_msvc2022_64

    - name: Configure CMake
      run: |
        $env:Qt6_DIR="C:\Qt\$env:Qt6_VERSION\msvc2022_64\lib\cmake"
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DQt6_DIR=$env:Qt6_DIR -DOpenCV_DIR=C:/opencv/build/x64/vc16/lib
    
    - name: Build Project
      run: |
        cmake --build build --config Release

        C:\Qt\$env:Qt6_VERSION\msvc2022_64\bin\windeployqt.exe build\Release\APO.exe
        cp C:\opencv\build\x64\bin\opencv_world4110.dll build\Release\
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/Release/


    - name: Run Tests
      run: |
        cd build
        ctest -C Release --output-on-failure

